Repository coopnorge/helm-base-chart, pull requests merged in 2023-11, with the labels that each got.

#18 feat: Add release drafter
  .github/workflows/release-drafter.yaml
Labels: minor, enhancements

#19 feat: Add chart version auto-updater
  .github/workflows/helm-chart-version-updater.yaml
  CODEOWNERS
Labels: minor, enhancements

#20 fix: set correct ref to value
  charts/coop-app-chart/templates/deployment.yaml
Labels: patch, bug-fix

#21 fix: use tcpSocket for grpc healtchecks
  charts/coop-app-chart/templates/deployment.yaml
Labels: patch, bug-fix

#24 fix: Trigger version updater on `created` and `edited` instead of `published`
  .github/workflows/helm-chart-version-updater.yaml
Labels: patch, bug-fix

#22 fix: add extra ignore for kube-ignore
  charts/coop-app-chart/values.yaml
Labels: patch, bug-fix

#23 fix: gprc transcoder virtual service
  charts/coop-app-chart/templates/virtualservice.yaml
Labels: patch, bug-fix

#26 fix: Remove github-review-bot from CODEOWNERS
  CODEOWNERS
Labels: patch, bug-fix

#28 fix: rewrite labels a bit to reduce restarting actions
  charts/coop-app-chart/templates/_helpers.tpl
  charts/coop-app-chart/templates/deployment.yaml
Labels: patch, bug-fix

#30 chore: Update release drafter version
  .github/workflows/release-drafter.yaml
  charts/coop-app-chart/Chart.yaml
Labels: patch, chore

#32 fix: write fixed chartname label instead of alias
  charts/coop-app-chart/templates/_helpers.tpl
Labels: patch, bug-fix

#36 fix: Get release tag another way
  .github/workflows/release-chart.yaml
Labels: patch, bug-fix

#39 docs: Add documentation for to the helm chart
  .github/workflows/build.yaml
  .gitignore
  README.md
  catalog-info.yaml
  charts/coop-app-chart/values.yaml
  docker-compose.yaml
  docker-compose/Dockerfile
  docs/index.md
  vale.ini
Labels: minor, enhancements, patch, chore

#37 chore: Add support for release of alpha versions
  .github/workflows/release-chart-workflow.yaml
  .github/workflows/release-chart.yaml
  .github/workflows/release-drafter.yaml
Labels: patch, chore

#45 fix: Avoid publishing alpha release for draft PRs
  .github/workflows/release-chart-workflow.yaml
  .github/workflows/release-drafter.yaml
Labels: patch, bug-fix

#47 fix: Make naming consistent to avoid bugs
  .github/workflows/release-chart.yaml
  .github/workflows/release-drafter.yaml
Labels: patch, bug-fix

#49 fix: Don't fail workflow if no changes to commit
  .github/workflows/release-chart-workflow.yaml
Labels: patch, bug-fix
