Repository coopnorge/helm-base-chart, pull requests merged in 2024-02, with the labels that each got.

#58 fix: Set healtcheck to correct value if path defined
  charts/coop-app-chart/templates/deployment.yaml
Labels: release-drafter:patch, release-drafter:bug-fix

#62 fix: Fix typo in datadog version label
  charts/coop-app-chart/templates/_helpers.tpl
Labels: release-drafter:patch, release-drafter:bug-fix

#60 feat!: use standard image format
  charts/coop-app-chart/templates/_helpers.tpl
  charts/coop-app-chart/templates/deployment.yaml
  charts/coop-app-chart/values.yaml
  docs/index.md
  examples/addons/values.yaml
  examples/grpc/values.yaml
  examples/http/values.yaml
  examples/multiple/values.yaml
Labels: release-drafter:major, release-drafter:breaking-change

#65 feat: add json schema to help with validation
  .github/workflows/build.yaml
  charts/coop-app-chart/values.schema.json
  charts/coop-app-chart/values.yaml
  docs/index.md
  examples/addons/charts/coop-app-chart
  examples/http/charts/coop-app-chart
  examples/multiple/charts/coop-app-chart
  examples/multiple/values.yaml
Labels: release-drafter:minor, release-drafter:enhancements

#67 chore: Fix typos and add command for generating lockfile
  docs/index.md
  examples/addons/values.yaml
  examples/grpc/values.yaml
  examples/multiple/values.yaml
Labels: release-drafter:patch, release-drafter:chore
