Repository coopnorge/helm-base-chart, pull requests merged in 2024-04, with the labels that each got.

#78 fix: prefix portname with http
  charts/coop-app-chart/templates/service.yaml
Labels: release-drafter:patch, release-drafter:bug-fix

#81 docs: Add titles to file samples
  docs/index.md
Labels: release-drafter:patch, release-drafter:chore

#82 feat: allow overriding http gRPC transcoder path
  charts/coop-app-chart/templates/virtualservice.yaml
  charts/coop-app-chart/values.schema.json
  charts/coop-app-chart/values.yaml
  examples/multiple/values.yaml
Labels: release-drafter:minor, release-drafter:enhancements
